library(data.table)
library(magrittr)
library(edgeR)
library(stringr)
library(clusterProfiler)
library(openxlsx)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(ggplot2)
library(pheatmap)
library(RColorBrewer)
library(PoiClaClu)
library(org.Hs.eg.db)
library(SummarizedExperiment)
library(reactome.db)
library(GO.db)
library(biomaRt)
library(ChIPseeker)
library(rtracklayer)
library(liftOver)
library(cbmR)
library(scales)
library(factoextra)
library(reshape2)
library(gridExtra)
library(vegan)
library(dplyr)
library(zoo)
library(gtable)
library(grid)
library(diffHic)
library(BSgenome.Hsapiens.UCSC.hg38)
library(csaw)
library(GenomicRanges)
library(clipr)
library(GenomicInteractions)
library(InteractionSet)
library(export)

source("1.ChIP/1.edgeR.R", local = new.env(), chdir = TRUE)
source("2.RNA/1.edgeR.R", local = new.env(), chdir = TRUE)
source("2.RNA/2.camera.R", local = new.env(), chdir = TRUE)
source("2.RNA/3.getGenesFromTerms.R", local = new.env(), chdir = TRUE)
source("2.RNA/figures/4.densityPlots.R", local = new.env(), chdir = TRUE)
source("2.RNA/figures/5.ecdfPlots.R", local = new.env(), chdir = TRUE)
source("2.RNA/figures/6.heatmaps.R", local = new.env(), chdir = TRUE)
source("2.RNA/figures/7.logFCs.R", local = new.env(), chdir = TRUE)
source("2.RNA/figures/8.dotPlot.R", local = new.env(), chdir = TRUE)
source("2.RNA/significant_in_both/9.significantInBoth.R", local = new.env(), chdir = TRUE)
source("3.cHiC/preparePromoters/1.makeBed.R", local = new.env(), chdir = TRUE)
source("3.cHiC/preparePromoters/2.fixPromoters.R", local = new.env(), chdir = TRUE)
source("3.cHiC/3.makeDatasets.R", local = new.env(), chdir = TRUE)
source("3.cHiC/secondaryStatistics/4.featureMaps.R", local = new.env(), chdir = TRUE)
source("3.cHiC/secondaryStatistics/5.promoterScores.R", local = new.env(), chdir = TRUE)
source("3.cHiC/6.exportBedPe.R", local = new.env(), chdir = TRUE)
source("3.cHiC/lookupTables/7.combinedDataSheets.R", local = new.env(), chdir = TRUE)
source("3.cHiC/figures/8.ecdf.R", local = new.env(), chdir = TRUE)
source("3.cHiC/figures/9.interactionsPerPromoter.R", local = new.env(), chdir = TRUE)
source("3.cHiC/figures/10.distanceBetweenFragment.R", local = new.env(), chdir = TRUE)
source("4.misc/SNP_vs_phenotype/multipleTestingCorrection.R", local = new.env(), chdir = TRUE)